version: "3"
services:
  db01:
    image: saleh1312\db01
    container_name: db01
    hostname: db01
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
    networks:
      - app_network

  mc01:
    image: memcached
    container_name: mc01
    hostname: mc01
    networks:
      - app_network

  rmq01:
    image: rabbitmq
    container_name: rmq01
    hostname: rmq01
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    networks:
      - app_network

  app01:
    image: saleh1312\db01
    container_name: app01
    hostname: app01
    networks:
      - app_network

  vproweb:
    image: web01
    container_name: web01
    hostname: app01
    ports:
      - "80:80"

networks:
  app_network:
    driver: bridge
