Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Function to configure clients for NRPE and monitoring
    def configure_client(config, name, ip, memory, vcpu, global_script , local_script)
        config.vm.define name do |client|
            client.vm.box = "bento/ubuntu-22.04"
            client.vm.hostname = name
            client.vm.network "private_network", ip: ip
            client.vm.boot_timeout = 5000
            client.vm.provider "virtualbox" do |vb|
                vb.memory = memory
                vb.cpus = vcpu
            end
            
            # Install and configure NRPE if a script path is provided

            client.vm.provision "shell", path: global_script, privileged: true

            client.vm.provision "shell", path: local_script, privileged: true

        end
    end
    
    ### Master VM ###
    configure_client(config, "controlplane", "10.0.0.10", 3096, 4, "./common.sh", "./control_plane.sh")

    ### Control 1 ###
    configure_client(config, "node01", "10.0.0.11", 3096, 4, "./common.sh", "./worker.sh")

    ### Control 2 ###
    configure_client(config, "node02", "10.0.0.12", 3096, 4, "./common.sh", "./worker.sh")

end
